version: '2'

services:
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   volumes:
  #     - ../frontend:/project/frontend
  backend:
    container_name: backend
    #image: php:fpm
    #build: ./base/php
    build: ./dev/php
    volumes:
      - ../backend:/project/backend
    #ports:
      #- "23:22"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes_from:
      #- frontend
      - backend
    volumes:
      - ./dev/nginx/conf/project.conf:/etc/nginx/conf.d/project.conf
    depends_on:
      #- frontend
      - backend
